/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['algorithm.js']) {
  _$jscoverage['algorithm.js'] = [];
  _$jscoverage['algorithm.js'][1] = 0;
  _$jscoverage['algorithm.js'][2] = 0;
  _$jscoverage['algorithm.js'][5] = 0;
  _$jscoverage['algorithm.js'][6] = 0;
  _$jscoverage['algorithm.js'][9] = 0;
  _$jscoverage['algorithm.js'][10] = 0;
  _$jscoverage['algorithm.js'][13] = 0;
  _$jscoverage['algorithm.js'][14] = 0;
}
_$jscoverage['algorithm.js'][1]++;
if ("undefined" === typeof exports) {
  _$jscoverage['algorithm.js'][2]++;
  exports = {};
}
_$jscoverage['algorithm.js'][5]++;
exports.aReverse = (function (array) {
  _$jscoverage['algorithm.js'][6]++;
  return array.reverse();
});
_$jscoverage['algorithm.js'][9]++;
exports.aPush = (function (array) {
  _$jscoverage['algorithm.js'][10]++;
  return array.push;
});
_$jscoverage['algorithm.js'][13]++;
exports.aPop = (function (array) {
  _$jscoverage['algorithm.js'][14]++;
  return array.pop;
});
_$jscoverage['algorithm.js'].source = ["if ('undefined' === typeof exports) {","\texports = {};","}","","exports.aReverse = function(array) {","\treturn array.reverse();","}","","exports.aPush = function(array) {","\treturn array.push;","}","","exports.aPop = function(array) {","\treturn array.pop;","}"];
