/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['myHttp.js']) {
  _$jscoverage['myHttp.js'] = [];
  _$jscoverage['myHttp.js'][1] = 0;
  _$jscoverage['myHttp.js'][3] = 0;
  _$jscoverage['myHttp.js'][4] = 0;
}
_$jscoverage['myHttp.js'][1]++;
var http = require("http");
_$jscoverage['myHttp.js'][3]++;
exports.get = (function (url, callback) {
  _$jscoverage['myHttp.js'][4]++;
  return http.get(url, callback);
});
_$jscoverage['myHttp.js'].source = ["var http = require('http');","","exports.get = function(url, callback) {","  return http.get(url, callback);","};"];
