/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['operator.js']) {
  _$jscoverage['operator.js'] = [];
  _$jscoverage['operator.js'][1] = 0;
  _$jscoverage['operator.js'][2] = 0;
  _$jscoverage['operator.js'][6] = 0;
  _$jscoverage['operator.js'][7] = 0;
  _$jscoverage['operator.js'][10] = 0;
  _$jscoverage['operator.js'][11] = 0;
}
_$jscoverage['operator.js'][1]++;
if ("undefined" === typeof exports) {
  _$jscoverage['operator.js'][2]++;
  exports = {};
}
_$jscoverage['operator.js'][6]++;
exports.sum = (function (a, b) {
  _$jscoverage['operator.js'][7]++;
  return a + b;
});
_$jscoverage['operator.js'][10]++;
exports.sub = (function (a, b) {
  _$jscoverage['operator.js'][11]++;
  return a - b;
});
_$jscoverage['operator.js'].source = ["if ('undefined' === typeof exports) {","\texports = {};","}","","","exports.sum = function(a, b) {","\treturn a+b;","}","","exports.sub = function(a, b) {","\treturn a-b;","}"];
